[package]
name = "graphemy_ffi"
version = "0.1.0"
edition = "2024"

[lib]
name = "_graphemy_ffi"
crate-type = ["cdylib"]

[dependencies]
graphemy = { git = "https://codeberg.org/zhuriel/graphemy.git", version = "0.6.0" }
svg = "0.18.0"
